junit_tests(
    name = 'tests',
    dependencies = [
        '3rdparty/intellij:sdk',
        '3rdparty/intellij:python-plugin',
        '3rdparty/intellij:scala-plugin',
        'jps-plugin',
        'src:pants-intellij-plugin-java'
    ],
    sources = rglobs('*.java')
)